version: '2'
services:
  zookeeper:
    image: talkdesk/zookeeper:3.4.8
    hostname: zk
  nimbus:
    image: talkdesk/storm-nimbus:1.0.1
    hostname: nimbus
    environment:
      - ZOOKEEPER_HOST=zk
    depends_on:
      - zookeeper
    links: 
      - zookeeper:zk
  supervisor:
    image: talkdesk/storm-supervisor:1.0.1
    environment:
      - ZOOKEEPER_HOST=zk
      - NIMBUS_HOST=nimbus
    depends_on:
      - zookeeper
    links: 
      - nimbus:nimbus
      - zookeeper:zk
  ui:
    image: talkdesk/storm-ui:1.0.1
    ports:
      - "8080:8080"
    environment:
      - ZOOKEEPER_HOST=zk
      - NIMBUS_HOST=nimbus
    depends_on:
      - zookeeper
    links: 
      - nimbus:nimbus
      - zookeeper:zk
