logging:
  level: INFO
  loggers:
    com.javaeeeee: DEBUG

#Server configuration.
server:
    applicationConnectors:
        - type: https
          port: 10514
          keyStorePath: /dwstart.keystore
          trustStorePath: /cacerts
          keyStorePassword: crimson
          validateCerts: false